remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
title: data_processing_Ukanazawa
description: Homepage for data_processing_Ukanazawa

logo: "/assets/images/logo.png"
color_scheme: light

# navigation
aux_links:
  "View on GitHub":
    - "//github.com/qingruiliu/data_processing_Ukanazawa"

# Enable search functionality
search_enabled: true
